controllers:
    resource: ../src/Controller/
    type: attribute

my_match_list:
    path: /api/match/me
    defaults:
        id: 1
    controller: App\Controller\Match\ListMyMatch
    methods: GET

match_list:
    path: /api/match/{id}
    defaults:
        id: 1
    controller: App\Controller\Match\ListMatch
    methods: GET

match_action:
    path: /api/match/action
    controller: App\Controller\Match\ActionMatch
    methods: POST

settings_list:
    path: /api/settings/{id}
    defaults:
        id: 1
    controller: App\Controller\Profil\Settings
    methods: GET

messages_list:
    path: /api/messaging/{my_id}/{id_recevier}
    controller: App\Controller\Messages\ListMessages
    methods: GET

message_send:
    path: /api/messaging/send
    defaults:
        id: 1
    controller: App\Controller\Messages\SendMessage
    methods: POST
